kind: pipeline
type: docker
name: default

steps:
#  - name: eslint check
#    image: node:14-alpine
#    commands:
#      - yarn
#      - yarn lint
#  - name: build
#    image: node:14-alpine
#    commands:
#      - yarn
#      - yarn build
#  - name: benchmark
#    image: node:14-alpine
#    environment:
#      LHCI_GITHUB_APP_TOKEN:
#        from_secret: LHCI_GITHUB_APP_TOKEN
#      LHCI_BUILD_CONTEXT__GIT_REMOTE: git@github.com:cchampou/beli.git
#    commands:
#      - apk add chromium
#      - yarn
#      - yarn build
#      - yarn lhci
  - name: deploy
    image: docker/compose:1.24.1
    commands:
      - docker-compose -p beli up -d --build web
    volumes:
      - name: docker
        path: /var/run/docker.sock
#    when:
#      event:
#        - promote
#      target:
#        - production

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock