kind: pipeline
type: docker
name: default

steps:
  - name: eslint check
    image: node:14-alpine
    commands:
      - yarn
      - yarn lint
  - name: build
    image: node:14-alpine
    commands:
      - yarn
      - yarn build