kind: pipeline
type: docker
name: default

steps:
#  - name: eslint check
#    image: node:14-alpine
#    commands:
#      - yarn
#      - yarn lint
#    depends_on:
#      - clone
#  - name: build
#    image: node:14-alpine
#    commands:
#      - yarn
#      - yarn build
#    depends_on:
#      - clone
  - name: benchmark
    image: node:14-alpine
    commands:
      - apk add chromium
      - yarn
      - yarn build
      - yarn lhci
    depends_on:
      - clone