version: "3.3"
services:
  web:
    build: .
    image: beli:latest
    ports:
    - 9000:80
    volumes:
    - ./config/default.conf.template:/etc/nginx/templates/default.conf.template
    labels:
      - traefik.http.routers.beli.rule=Host(`beli.cchampou.me`)
      - traefik.http.routers.beli.tls=true
      - traefik.http.routers.beli.loadbalancer.server.port=9000
      - traefik.http.routers.beli.tls.certresolver=main